// Common hospital departments/specialties, offered as suggestions wherever a
// department is picked (doctor referrals, adding a doctor). Not an
// enforced allow-list -- department stays free text so a hospital's own
// naming (or a department not listed here) can still be typed.
export const HOSPITAL_DEPARTMENTS = [
  "General Medicine",
  "General Surgery",
  "Emergency Medicine",
  "Family Medicine",
  "Internal Medicine",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Neurology",
  "Neurosurgery",
  "Orthopedics",
  "Obstetrics & Gynecology",
  "Pediatrics",
  "Oncology",
  "Radiology",
  "Anesthesiology",
  "Psychiatry",
  "Dermatology",
  "Ophthalmology",
  "Otorhinolaryngology (ENT)",
  "Urology",
  "Nephrology",
  "Gastroenterology",
  "Hepatology",
  "Pulmonology / Respiratory Medicine",
  "Endocrinology",
  "Rheumatology",
  "Hematology",
  "Infectious Diseases",
  "Plastic & Reconstructive Surgery",
  "Vascular Surgery",
  "Pathology",
  "Dentistry / Oral & Maxillofacial Surgery",
  "Physiotherapy / Rehabilitation Medicine",
  "Geriatrics",
  "Palliative Care",
  "Intensive Care / Critical Care",
  "Radiotherapy",
  "Sports Medicine",
  "Forensic Medicine",
];
